### ISSUE TITLE
Client and server don't extract all config files

### ISSUE THREAD

**Issue by SwamiUmami** [opensoldat/opensoldat#83]
**Current behaviour**
Client: `taunts.cfg` is missing in `configs` folder
Server: `mapslist.txt`, `remote.txt`, `bots` folder, `weapons.ini`, `weapons_realistic.ini` are missing in `configs` folder

**Expected behaviour**
Client: `client.cfg`, `taunts.cfg` are present in `configs` folder
Server: `mapslist.txt`, `remote.txt`, `bots` folder, `server.cfg`, `weapons.ini`, `weapons_realistic.ini`, `banned.txt`, `bannedhw.txt` are present in `configs` folder

**More thoughts**
I don't know all code, but what about `mod.ini`? Shouldn't it be treated as a config file? It seems only client uses it

**Tasks**
- [ ] Make decision on #82, because it affects all implementation. Contributors need to know if their pull request will be accepted, or it's waste of time
- [ ] Make fixes in [base repository](https://github.com/Soldat/base) (organize config files, set reasonable defaults). Do you want separate issue in [base](https://github.com/Soldat/base)?
- [ ] Make new assets release in [base repository](https://github.com/Soldat/base)
- [ ] Make fixes in this repository - make sure config files are unpacked on first run, or change logic as presented in #82 

**How to test?**
Make client-only and server-only builds. You will need Soldat assets from base repository, so probably change `cmake_modules/SoldatAssets.cmake` to download new release (mentioned in 3rd task), or download manually and copy to `bin` folder. Verify that all config files are present in `bin/configs` folder
